imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  nodes:
    my-tests:
      root_path: "/home/scrutinizer/build/" 
      environment:
        php:
          version: 8.1
      commands:

        # - composer install --no-interaction --prefer-dist
        - pwd
        - ls -la build
        - XDEBUG_MODE=coverage vendor/bin/phpunit
          coverage:
            file: "build/coverage.clover"
            format: "php-clover"
    analysis:
      tests:
        override:
          - php-scrutinizer-run
