imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  environment:
    apt_packages:
      - openssl
  nodes:
    my-tests:
      environment:
        php:
          version: 8.1
      commands:
        - command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
          coverage:
            file: "docs/coverage.clover"
            format: "php-clover"
    analysis:
      tests:
        override:
          - php-scrutinizer-run
