imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  before_commands:
    - composer install --no-interaction --prefer-dist
  nodes:
    my-tests:
      environment:
        php:
          version: 8.1
      commands:
        - command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
          coverage:
            file: "build/coverage.clover"
            format: "php-clover"
    analysis:
      tests:
        override:
          - php-scrutinizer-run
